# Generated by Django 6.0.6 on 2026-06-18 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_limite_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('opcion_multiple_una', 'Opcion multiple (1 respuesta)'), ('opcion_multiple_varias', 'Opcion multiple (varias respuestas)'), ('verdadero_falso', 'Verdadero / Falso'), ('completar_espacios', 'Completar espacios'), ('relacionar_columnas', 'Relacionar columnas'), ('ordenamiento', 'Ordenamiento'), ('respuesta_numerica', 'Respuesta numerica'), ('menu_desplegable', 'Menu desplegable'), ('seleccion_imagen', 'Seleccion en imagen'), ('respuesta_corta', 'Respuesta corta'), ('ensayo', 'Ensayo'), ('subida_archivo', 'Subida de archivo'), ('respuesta_imagen', 'Respuesta con imagen'), ('editor_codigo', 'Editor de codigo'), ('escala_valoracion', 'Escala de valoracion')], max_length=30)),
                ('enunciado', models.TextField()),
                ('puntaje', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('respuesta_correcta', models.JSONField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.quiz')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('criterios', models.TextField(blank=True)),
                ('fecha_limite', models.DateTimeField()),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=dict)),
                ('nota_automatica', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nota_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de quiz',
                'verbose_name_plural': 'Respuestas de quiz',
                'unique_together': {('quiz', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], default='pendiente', max_length=15)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='evaluaciones.tarea')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'unique_together': {('tarea', 'usuario')},
            },
        ),
    ]
